language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 2.7
    env: USE_FREETYPE=false
  - os: linux
    sudo: required
    python: 2.7
    env: USE_FREETYPE=true
  - os: linux
    sudo: required
    python: 3.4
    env: USE_FREETYPE=false
  - os: linux
    sudo: required
    python: 3.4
    env: USE_FREETYPE=true
  - os: linux
    sudo: required
    python: 3.5
    env: USE_FREETYPE=false
  - os: linux
    sudo: required
    python: 3.5
    env: USE_FREETYPE=true
  - os: linux
    sudo: required
    python: 3.6
    env: USE_FREETYPE=false
  - os: linux
    sudo: required
    python: 3.6
    env: USE_FREETYPE=true
  - os: osx
    language: generic
    env: USE_FREETYPE=false USE_PYTHON=2
  - os: osx
    language: generic
    env: USE_FREETYPE=true USE_PYTHON=2
  - os: osx
    language: generic
    env: USE_FREETYPE=false USE_PYTHON=3
  - os: osx
    language: generic
    env: USE_FREETYPE=true USE_PYTHON=3
before_install:
  # python 2 is installed for osx already
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        if [[ "$USE_PYTHON" == "3" ]]; then
            brew upgrade python;
        fi;
    fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get update -qq;
        pip install pillow;
    else
        brew install libtiff libjpeg webp little-cms2;
        if [[ "$USE_PYTHON" == "3" ]]; then
            pip3 install pillow numpy;
        else
            pip2 install pillow numpy;
        fi
    fi

  - if [[ "$USE_FREETYPE" == "true" ]]; then
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            sudo apt-get install -qq libfreetype6-dev;
        else
            brew install freetype;
        fi
    fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$USE_PYTHON" == "3" ]]; then
        /usr/local/bin/python3 -V;
        /usr/local/bin/python3 setup.py build_ext -i;
        /usr/local/bin/python3 selftest.py;
      else
        /usr/local/bin/python2 -V;
        /usr/local/bin/python2 setup.py build_ext -i;
        /usr/local/bin/python2 selftest.py;
      fi;
    else
        which python;
        python -V;
        python setup.py build_ext -i;
        python selftest.py;
    fi;
deploy:
  provider: pypi
  user: dhoese
  password:
    secure: CYnfdweDHxSlPfks5YDZp9w4i5q4m/iUbIRrt37oHWhWVpnHa19yhk4BOBig5dAVJ5L/nYI/qz5bdE7NNubaXNnJTszhgK6RNRKg0LD80zliJxtCBXPnj8fvCgRKeQieiOurjyy4t0lEfeIVhEaEut9o3CuJXpONh9Zf8oL698Y=
  on:
    tags: true
    repo: pytroll/aggdraw
    python: 3.6
    os: linux
    condition: "$USE_FREETYPE == true"
    distributions: sdist
