environment:
  global:
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "latest"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    CONDA_DEPENDENCIES: "sphinx pillow coveralls coverage"
    CONDA_CHANNELS: "conda-forge"

  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      NUMPY_VERSION: "stable"
      BUILDMODE: "CI-HELPERS"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      NUMPY_VERSION: "stable"
      BUILDMODE: "CI-HELPERS"

    - PYTHON: "C:\\Python36_32"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      NUMPY_VERSION: "stable"
      BUILDMODE: "CI-HELPERS"

    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      NUMPY_VERSION: "stable"
      BUILDMODE: "CI-HELPERS"

    - BUILDMODE: "CIBUILDWHEEL"
      CIBW_TEST_REQUIRES: "numpy pillow"
      CIBW_TEST_COMMAND: "python {project}\\selftest.py"

install:
  - if [%BUILDMODE%]==["CI-HELPERS"] git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - if [%BUILDMODE%]==["CI-HELPERS"] powershell ci-helpers/appveyor/install-miniconda.ps1
  - if [%BUILDMODE%]==["CI-HELPERS"] SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - if [%BUILDMODE%]==["CI-HELPERS"] activate test
    
build: false  # Not a C# project, build stuff at the test step instead.

build_script:
  - if [%BUILDMODE%]==["CIBUILDWHEEL"] pip install cibuildwheel==0.10.0
  - if [%BUILDMODE%]==["CIBUILDWHEEL"] cibuildwheel --output-dir dist

test_script:
  - if [%BUILDMODE%]==["CI-HELPERS"] [%CMD_IN_ENV%] pip install -e .
  - if [%BUILDMODE%]==["CI-HELPERS"] [%CMD_IN_ENV%] python selftest.py

after_test:
  - if [%BUILDMODE%]==["CI-HELPERS"] [%CMD_IN_ENV%] python setup.py bdist_wheel bdist_wininst
  - ps: "ls dist"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
